### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by mpm2050**

### CODE REVIEW

**Comment by anseki** [comment]
Hi @mpm2050, thank you for the PR.
Sorry, this PR can't be merged because:
* No description was provided at all. I couldn't understand the "Add files via upload" that you said.
* Too much files (8 files) were changed meaninglessly. https://github.com/anseki/jquery-ui-autocomplete-scroll/pull/6/files

**Comment by anseki** [comment]
Thank you for your time. :smile:

**Comment by mpm2050** [comment]
here you can see what changed GitHub - mpm2050/jquery-ui-autocomplete-scroll: Scrollable jQuery UI Autocomplete for long item list was done
New parameter is introduced 
setWidthAsTextBox : true | false

and the screen shots also added.
    On Thursday, 20 January, 2022, 05:59:43 pm IST, anseki ***@***.***> wrote:  
 
 


Hi @mpm2050, thank you for the PR.
Sorry, this PR can't be merged because:
   
   - No description was provided at all. I couldn't understand the "Add files via upload" that you said.
   - Too much files (8 files) were changed meaninglessly. https://github.com/anseki/jquery-ui-autocomplete-scroll/pull/6/files

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mpm2050** [comment]
https://github.com/mpm2050/jquery-ui-autocomplete-scroll

    On Monday, 24 January, 2022, 07:57:26 am IST, Pitchaimuthu ***@***.***> wrote:  
 
  here you can see what changed GitHub - mpm2050/jquery-ui-autocomplete-scroll: Scrollable jQuery UI Autocomplete for long item list was done
New parameter is introduced 
setWidthAsTextBox : true | false

and the screen shots also added.
    On Thursday, 20 January, 2022, 05:59:43 pm IST, anseki ***@***.***> wrote:  
 
 


Hi @mpm2050, thank you for the PR.
Sorry, this PR can't be merged because:
   
   - No description was provided at all. I couldn't understand the "Add files via upload" that you said.
   - Too much files (8 files) were changed meaninglessly. https://github.com/anseki/jquery-ui-autocomplete-scroll/pull/6/files

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by anseki** [comment]
Hi @mpm2050, thank you for the comments.
Sorry, I couldn't understand those. It seems that those are duplicated. Maybe you mistook it, you sent e-mails instead of posting on the GitHub website.
You had better access to https://github.com/anseki/jquery-ui-autocomplete-scroll/pull/6 via web-browser.

**Pull request closed without merging**
